#######################################################################
# Headless service for the wazuh-manager-client StatefulSet
#######################################################################

apiVersion: v1
kind: Service
metadata:
  name: wazuh-client
  namespace: wazuh
  labels:
    app: wazuh-client
spec:
  ports:
    - name: wazuh-clusterd
      port: 1516
      targetPort: 1516
  clusterIP: None
  selector:
    wazuh-manager-role: client
