#######################################################################
# Kubernetes StatefulSet for the Wazuh manager master node
#
# We deploy only one replica here because Wazuh is not yet supporting
# a multi-master setup
#######################################################################

apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: wazuh-manager-master
  namespace: wazuh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wazuh-manager
      wazuh-manager-role: master
  serviceName: wazuh-master
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: wazuh-manager
        wazuh-manager-role: master
      name: wazuh-manager-master
    spec:
      volumes:
        - name: config
          configMap:
            name: wazuh-manager-master-conf
      containers:
        - name: wazuh-manager
          image: 'wazuh/wazuh:3.2.0_6.2.1'
          resources:
            requests:
              cpu: 500m
              memory: 256Mi
            limits:
              cpu: 1
              memory: 512Mi
          volumeMounts:
            - name: config
              mountPath: /wazuh-config-mount/etc/ossec.conf
              subPath: ossec.conf
              readOnly: true
            - name: wazuh-manager-master
              mountPath: /var/ossec/data
            - name: wazuh-manager-master
              mountPath: /etc/postfix
          ports:
            - containerPort: 1514
            - containerPort: 1515
            - containerPort: 1516
            - containerPort: 55000
  volumeClaimTemplates:
    - metadata:
        name: wazuh-manager-master
        namespace: wazuh
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: gp2-encrypted-retained
        resources:
          requests:
            storage: 10Gi
